version: '3.4'

services:
  global_rstudio:
    build:
      context: ./rstudio_docker
    container_name: global_rstudio
    volumes:
      - /home/${USERNAME}/:/home/${USERNAME}/
      - /tank/${USERNAME}/:/tank/${USERNAME}/
      - /home/${USERNAME}/.ssh:/home/${USERNAME}/.ssh
      - /home/${USERNAME}/Zotero:/home/${USERNAME}/Zotero
      - /opt/local/renv/cache:/home/${USERNAME}/renv/cache
      - /opt/local/AnnotationHub/cache:/home/${USERNAME}/.cache/AnnotationHub
      - /home/${USERNAME}/r_dev_projects/rstudio_config_dir:/home/${USERNAME}/.config/rstudio
    restart:
      unless-stopped
    ports:
      - 6969:8787
    env_file: ./rstudio_docker/rstudio.env

